//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_manangementEntities : DbContext
    {
        public project_manangementEntities()
            : base("name=project_manangementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bookedshowcase> bookedshowcases { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<dailyworkingrecord> dailyworkingrecords { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<salesrecord> salesrecords { get; set; }
        public DbSet<salesrecord_product> salesrecord_product { get; set; }
        public DbSet<showcase> showcases { get; set; }
        public DbSet<showcase_product> showcase_product { get; set; }
        public DbSet<showcase_rentrecord> showcase_rentrecord { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<tenant> tenants { get; set; }
    }
}
