//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesrecord_product
    {
        public int SalesID { get; set; }
        public int ProductID { get; set; }
        public int ShowcaseID { get; set; }
        public int Qty { get; set; }
        public int eachFee { get; set; }
        public int Discount { get; set; }
    
        public virtual product product { get; set; }
        public virtual salesrecord salesrecord { get; set; }
    }
}
