//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesrecord
    {
        public salesrecord()
        {
            this.salesrecord_product = new HashSet<salesrecord_product>();
        }
    
        public int SalesID { get; set; }
        public System.DateTime SalesDATETIME { get; set; }
        public int StoreID { get; set; }
        public int TotalSalesAmount { get; set; }
        public int Tender { get; set; }
        public int Changecost { get; set; }
        public int StaffID { get; set; }
        public string Paymethod { get; set; }
    
        public virtual ICollection<salesrecord_product> salesrecord_product { get; set; }
        public virtual staff staff { get; set; }
    }
}
