//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.dailyworkingrecords = new HashSet<dailyworkingrecord>();
            this.salesrecords = new HashSet<salesrecord>();
        }
    
        public int StaffID { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_HKIDNumber { get; set; }
        public string Staff_Username { get; set; }
        public string Staff_password { get; set; }
        public string StaffPosition { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int HourSalary { get; set; }
        public System.DateTime HireDate { get; set; }
        public bool isFulltime { get; set; }
    
        public virtual ICollection<dailyworkingrecord> dailyworkingrecords { get; set; }
        public virtual ICollection<salesrecord> salesrecords { get; set; }
    }
}
