//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public tenant()
        {
            this.bookedshowcases = new HashSet<bookedshowcase>();
            this.products = new HashSet<product>();
            this.showcase_rentrecord = new HashSet<showcase_rentrecord>();
        }
    
        public int TenantID { get; set; }
        public string Name { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateTimeofCreation { get; set; }
        public string Tenant_Username { get; set; }
        public string Tenant_Password { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Tenant_HKIDNumber { get; set; }
        public int CommisionRate { get; set; }
    
        public virtual ICollection<bookedshowcase> bookedshowcases { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<showcase_rentrecord> showcase_rentrecord { get; set; }
    }
}
